# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Starlight(object):
    def setupUi(self, Project_Starlight):
        Project_Starlight.setObjectName("Project_Starlight")
        Project_Starlight.setFixedSize(1102, 870)
        self.centralwidget = QtWidgets.QWidget(Project_Starlight)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 1091, 831))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Screenshot (31).png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 140, 881, 521))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Screen.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        # self.label_3 = QtWidgets.QLabel(self.centralwidget)
        # self.label_3.setGeometry(QtCore.QRect(140, 160, 231, 81))
        # self.label_3.setText("")
        # self.label_3.setPixmap(QtGui.QPixmap("Screenshot (311).png"))
        # self.label_3.setScaledContents(True)
        # self.label_3.setObjectName("label_3")
        # self.label_4 = QtWidgets.QLabel(self.centralwidget)
        # self.label_4.setGeometry(QtCore.QRect(740, 160, 231, 81))
        # self.label_4.setText("")
        # self.label_4.setPixmap(QtGui.QPixmap("Screenshot (311).png"))
        # self.label_4.setScaledContents(True)
        # self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(132, 597, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background:rgb(0, 0, 175)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(850, 580, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setAutoFillBackground(True)
        self.pushButton_2.setStyleSheet("background:rgb(0, 0, 175)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(120, 150, 261, 101))
        self.textBrowser.setStyleSheet("background:transparent; \n"
                                         "font-size: 41px; \n"
                                         "font-family: Monaco; \n"
                                         "font-weight: Bold; \n"
                                         "color: rgb(0, 0, 175)")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(730, 150, 261, 101))
        self.textBrowser_2.setAutoFillBackground(True)
        self.textBrowser_2.setStyleSheet("background:transparent; \n"
                                         "font-size: 41px; \n"
                                         "font-family: Monaco; \n"
                                         "font-weight: Bold; \n"
                                         "color: rgb(0, 0, 175)")
        self.textBrowser_2.setObjectName("textBrowser_2")
        Project_Starlight.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Project_Starlight)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1102, 26))
        self.menubar.setObjectName("menubar")
        Project_Starlight.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Project_Starlight)
        self.statusbar.setObjectName("statusbar")
        Project_Starlight.setStatusBar(self.statusbar)

        self.retranslateUi(Project_Starlight)
        QtCore.QMetaObject.connectSlotsByName(Project_Starlight)

    def retranslateUi(self, Project_Starlight):
        _translate = QtCore.QCoreApplication.translate
        Project_Starlight.setWindowTitle(_translate("Project_Starlight", "Project_Starlight"))
        self.pushButton.setText(_translate("Project_Starlight", "RUN"))
        self.pushButton_2.setText(_translate("Project_Starlight", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Project_Starlight = QtWidgets.QMainWindow()
    ui = Ui_Starlight()
    ui.setupUi(Project_Starlight)
    Project_Starlight.show()
    sys.exit(app.exec_())
